---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "spinnaker.fullname" . }}-halyard
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ template "spinnaker.fullname" . }}-halyard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spinnaker.fullname" . }}-halyard
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
